name: CI

on:
  push:
    branches:
      - master
      - feature/github-actions
      - feature/snap
    tags:
      - '*'

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Test
        run: docker-compose -f $GITHUB_WORKSPACE/zoonavigator-api/docker-compose.test.yml up --exit-code-from=sut

  test-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Test
        run: docker-compose -f $GITHUB_WORKSPACE/zoonavigator-web/docker-compose.test.yml up --exit-code-from=sut

  release-docker:
    runs-on: ubuntu-latest

    needs:
      - test-api
      - test-web

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get version
        id: version
        uses: battila7/get-version-action@v2

      - name: Docker Build
        id: build
        run: |
          TAG="${{ steps.get_version.outputs.version-without-v }}"

          # is this a tagged push?
          if [[ -z "$TAG" ]];
          then
              APP_VERSION=latest-${GITHUB_SHA::12}
              DOCKER_TAG="latest"
          else
              APP_VERSION=$TAG
              DOCKER_TAG=$TAG
          fi

          # set image name
          IMAGE_NAME="elkozmon/zoonavigator:${DOCKER_TAG}"
          echo "::set-output name=image_name::$IMAGE_NAME"

          # is docker tag semver?
          if [[ $DOCKER_TAG =~ ^[0-9]+(\.[0-9]+){2,3}$ ]];
          then
              DOCS_URL="https://zoonavigator.elkozmon.com/en/${DOCKER_TAG}"
          else
              DOCS_URL="https://zoonavigator.elkozmon.com/en/latest"
          fi

          docker build \
            --build-arg APP_VERSION=$APP_VERSION \
            --build-arg DOCS_URL=$DOCS_URL \
            --build-arg VCS_REF=$(git rev-parse --short HEAD) \
            --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
            -t $IMAGE_NAME \
            -f build/docker/Dockerfile \
            .

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_PASSWORD }}

      - name: Docker Push
        run: docker push ${{ steps.build.outputs.image_name }}

      - name: Microbadger webhook
        uses: muinmomin/webhook-action@v1.0.0
        with:
          url: ${{ secrets.MICROBADGER_WEBHOOK_URL }}

  release-snap:
    runs-on: ubuntu-latest

    needs:
      - test-api
      - test-web

    steps:
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}

      - name: Snap Build
        run: |
          echo TODO

      - name: Snap Push
        run: |
          echo TODO
